version: '3'

volumes:
  mongovolume:

services:
  praypayserver:
    image: praypay-server
    build: .
    # command: yarn start # node index.js
    ports:
      - "3000:3000"
    volumes:
      - ./praypayserver:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo

  mongo:
    image: "mongo"
    ports:
      - "27017:27017"
    volumes:
      - mongovolume:/data/db

  adminmongo:
    image: "mrvautin/adminmongo"
    environment:
      - HOST=0.0.0.0
    ports:
      - "1234:1234"
